# Part III: Chi-Squared Test
OBJECTIVE: Chi-Square Test of Independence for analyzing how certain key features
of the dataset are related to social media usage
DATASET: “Students Social Media Addiction.csv”
DATASET DESCRIPTION: Students’ Distraction & Social Media Addiction Dataset;
As quoted from Kaggle, “A dataset exploring how social media affects students’ daily
life, study patterns; Includes data on how much students use social media daily, and
whether it affects their academic performance”. More details can be found here
PRELIMINARY:
Form two new categorical features as follows:
1. “Usage” and fill the values as “Overuse” or “Controlled ” based on the correspond-
ing feature “Avg Daily Usage Hours” ≥ or < median of the values, respectively.
2. “Sleep” and fill the values as “Sufficient” or “Insufficient” based on the corre-
sponding variable Sleep Hours Per Night ≥7 or <7, respectively.
TASK:
Generate the contingency table and apply the Chi-Square Test of Independence on each
of the following pairs formed by the respective features and “Usage”.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Students Social Media Addiction.csv")

In [5]:
df

Student_ID  Age  Gender Academic_Level     Country  \
0             1   19  Female  Undergraduate  Bangladesh   
1             2   22    Male       Graduate       India   
2             3   20  Female  Undergraduate         USA   
3             4   18    Male    High School          UK   
4             5   21    Male       Graduate      Canada   
..          ...  ...     ...            ...         ...   
700         701   20  Female  Undergraduate       Italy   
701         702   23    Male       Graduate      Russia   
702         703   21  Female  Undergraduate       China   
703         704   24    Male       Graduate       Japan   
704         705   19  Female  Undergraduate      Poland   

     Avg_Daily_Usage_Hours Most_Used_Platform Affects_Academic_Performance  \
0                      5.2          Instagram                          Yes   
1                      2.1            Twitter                           No   
2                      6.0             TikTok                          Yes   
3                      3.0            YouTube                           No   
4                      4.5           Facebook                          Yes   
..                     ...                ...                          ...   
700                    4.7             TikTok                           No   
701                    6.8          Instagram                          Yes   
702                    5.6             WeChat                          Yes   
703                    4.3            Twitter                           No   
704                    6.2           Facebook                          Yes   

     Sleep_Hours_Per_Night  Mental_Health_Score Relationship_Status  \
0                      6.5                    6     In Relationship   
1                      7.5                    8              Single   
2                      5.0                    5         Complicated   
3                      7.0                    7              Single   
4                      6.0                    6     In Relationship   
..                     ...                  ...                 ...   
700                    7.2                    7     In Relationship   
701                    5.9                    4              Single   
702                    6.7                    6     In Relationship   
703                    7.5                    8              Single   
704                    6.3                    5              Single   

     Conflicts_Over_Social_Media  Addicted_Score  
0                              3               8  
1                              0               3  
2                              4               9  
3                              1               4  
4                              2               7  
..                           ...             ...  
700                            2               5  
701                            5               9  
702                            3               7  
703                            2               4  
704                            4               8  

[705 rows x 13 columns]

In [6]:
median = df["Avg_Daily_Usage_Hours"].median()

In [9]:
import numpy as np

In [22]:
df["Usage"] = np.where(df['Avg_Daily_Usage_Hours']>median , "Overuse" , "Controlled")

In [23]:
df["Sleep"] = np.where(df['Sleep_Hours_Per_Night']>=7 , "Sufficient" , "Insufficient")

In [24]:
ct1 = pd.crosstab(index = df['Academic_Level'] , columns = df['Usage'])
display(ct1)

Usage           Controlled  Overuse
Academic_Level                     
Graduate               181      144
High School              2       25
Undergraduate          194      159

In [25]:
ct2 = pd.crosstab(index = df['Gender'] , columns = df['Usage'])
display(ct2)

Usage   Controlled  Overuse
Gender                     
Female         183      170
Male           194      158

In [26]:
ct3 = pd.crosstab(index = df['Sleep'] , columns = df['Usage'])
display(ct3)

Usage         Controlled  Overuse
Sleep                            
Insufficient          58      301
Sufficient           319       27

In [46]:
import numpy as np
from scipy.stats import chi2_contingency

res = chi2_contingency(ct1)
display(res.statistic)
display(res.pvalue)
display(res.dof)
display(res.expected_freq)

23.985348536176012

6.189388477891447e-06

2

array([[173.79432624, 151.20567376],
       [ 14.43829787,  12.56170213],
       [188.76737589, 164.23262411]])

In [47]:
res2 = chi2_contingency(ct2)
display(res2.statistic)
display(res2.pvalue)
display(res2.dof)
display(res2.expected_freq)

0.6327372617471668

0.4263530425067472

1

array([[188.76737589, 164.23262411],
       [188.23262411, 163.76737589]])

In [48]:
res3 = chi2_contingency(ct3)
display(res3.statistic)
display(res3.pvalue)
display(res3.dof)
display(res3.expected_freq)

406.43138556610666

2.192453391657803e-90

1

array([[191.97588652, 167.02411348],
       [185.02411348, 160.97588652]])

In [49]:
thr1 = 3.841
thr2 = 5.991

data = {'Features': ['Academic Level', 'Gender', 'Sleep'],
        'Chi-Square Statistic': [res.statistic, res2.statistic, res3.statistic],
        'Threshould' : [5.991 , 3.841 ,3.841]
}

df = pd.DataFrame(data)
print(df)

         Features  Chi-Square Statistic  Threshould
0  Academic Level             23.985349       5.991
1          Gender              0.632737       3.841
2           Sleep            406.431386       3.841


In [50]:
df["Is related to Usage"] = np.where(df['Chi-Square Statistic']>=df['Threshould'] , "YES" , "NO")

In [51]:
df

Features  Chi-Square Statistic  Threshould Is related to Usage
0  Academic Level             23.985349       5.991                 YES
1          Gender              0.632737       3.841                  NO
2           Sleep            406.431386       3.841                 YES